/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScamShieldRouteImport } from './routes/scam-shield'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PersonalizeRouteImport } from './routes/personalize'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamShieldRoute = ScamShieldRouteImport.update({
  id: '/scam-shield',
  path: '/scam-shield',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizeRoute = PersonalizeRouteImport.update({
  id: '/personalize',
  path: '/personalize',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/personalize': typeof PersonalizeRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/scam-shield': typeof ScamShieldRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/personalize': typeof PersonalizeRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/scam-shield': typeof ScamShieldRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/personalize': typeof PersonalizeRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/scam-shield': typeof ScamShieldRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/personalize'
    | '/profile'
    | '/reset-password'
    | '/results'
    | '/scam-shield'
    | '/signup'
    | '/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/personalize'
    | '/profile'
    | '/reset-password'
    | '/results'
    | '/scam-shield'
    | '/signup'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/personalize'
    | '/profile'
    | '/reset-password'
    | '/results'
    | '/scam-shield'
    | '/signup'
    | '/subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PersonalizeRoute: typeof PersonalizeRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultsRoute: typeof ResultsRoute
  ScamShieldRoute: typeof ScamShieldRoute
  SignupRoute: typeof SignupRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam-shield': {
      id: '/scam-shield'
      path: '/scam-shield'
      fullPath: '/scam-shield'
      preLoaderRoute: typeof ScamShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalize': {
      id: '/personalize'
      path: '/personalize'
      fullPath: '/personalize'
      preLoaderRoute: typeof PersonalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PersonalizeRoute: PersonalizeRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultsRoute: ResultsRoute,
  ScamShieldRoute: ScamShieldRoute,
  SignupRoute: SignupRoute,
  SubscriptionsRoute: SubscriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
